/* REPLACE START: app.js（FATISM 多頁共用｜高質量＋全方位互動） */
(()=>{"use strict";
/* ====== 基礎工具 ====== */
const $=q=>document.querySelector(q),$$=q=>document.querySelectorAll(q),on=(t,e,h,o)=>t&&t.addEventListener(e,h,o),throttle=(fn,ms=120)=>{let t=0;return(...a)=>{const n=Date.now();if(n-t>=ms){t=n;fn.apply(null,a)}}},isReduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches||false;
/* ====== 主題切換（localStorage＋系統偏好） ====== */
const themeBtn=$("#themeBtn"),themeIcon=$("#themeIcon");(function initTheme(){const saved=localStorage.getItem("theme");const prefers=(!saved&&window.matchMedia?.("(prefers-color-scheme: dark)").matches)?"dark":"light";const cur=saved||prefers;document.documentElement.setAttribute("data-theme",cur);if(themeIcon)themeIcon.textContent=cur==="dark"?"🌙":"🌞"})();on(themeBtn,"click",()=>{const cur=document.documentElement.getAttribute("data-theme")||"light";const nxt=cur==="dark"?"light":"dark";document.documentElement.setAttribute("data-theme",nxt);localStorage.setItem("theme",nxt);if(themeIcon)themeIcon.textContent=nxt==="dark"?"🌙":"🌞"});
/* ====== 導覽欄（Drawer）＋可存取性 ====== */
const menuBtn=$("#menuBtn"),drawer=$("#drawer"),overlay=$("#overlay");let lastFocus=null;const trapKeys=e=>{if(e.key!=="Tab")return;const focusables=drawer?.querySelectorAll('a[href],button,[tabindex]:not([tabindex="-1"])');if(!focusables||!focusables.length)return;const f=[...focusables].filter(el=>!el.hasAttribute("disabled"));const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};const openDrawer=()=>{if(!drawer)return;lastFocus=document.activeElement;drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";document.addEventListener("keydown",trapKeys);const first=drawer.querySelector('a,button,[tabindex]:not([tabindex="-1"])');first&&first.focus()};const closeDrawer=()=>{if(!drawer)return;drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");document.body.style.overflow="";document.removeEventListener("keydown",trapKeys);lastFocus&&lastFocus.focus()};on(menuBtn,"click",openDrawer);on(overlay,"click",closeDrawer);drawer?.querySelectorAll("[data-close]")?.forEach(a=>on(a,"click",closeDrawer));on(document,"keydown",e=>{if(e.key==="Escape"&&drawer?.classList.contains("open"))closeDrawer()});
/* ====== 平滑錨點滾動（避免 Header 遮住，偏移 68px） ====== */
const SCROLL_OFF=68;$$('a[href^="#"]').forEach(a=>on(a,"click",e=>{const id=a.getAttribute("href");if(id&&id.length>1){const el=$(id);if(!el)return; e.preventDefault();const y=el.getBoundingClientRect().top+window.scrollY-SCROLL_OFF;window.scrollTo({top:y,behavior:"smooth"})}}));
/* ====== 導航高亮（跨頁） ====== */
(function markActiveNav(){const path=location.pathname.split("/").pop()||"index.html";$$(".nav a").forEach(link=>{const href=link.getAttribute("href");if(!href)return;const clean=href.includes("#")?href.split("#")[0]:href;if(clean===path||(clean==="index.html"&&path===""))link.setAttribute("aria-current","page");else link.removeAttribute("aria-current")})})();
/* ====== Reveal 進場動畫（IntersectionObserver） ====== */
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");io.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach(el=>io.observe(el));
/* ====== 版權年份 ====== */
const y=$("#y");if(y)y.textContent=new Date().getFullYear();
/* ====== 圖片延遲處理（可選：若你使用 .skeleton） ====== */
$$("img[data-src]").forEach(img=>{const o=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){img.src=img.dataset.src;img.removeAttribute("data-src");o.disconnect()}})},{rootMargin:"200px"});o.observe(img)});
/* ====== Emoji 漂浮背景（高質量互動＋節能） ====== */
const EmojiSky=(()=>{const CFG={emojis:['🍳','🥚','☕️','🍓','🍞','🍪','🍰','🧋','🥐','🥑','🐣','⭐','🍯','🧈','🍵'],density:{xl:2,lg:4,md:6,sm:6},speed:[22,36],delay:[0,8],sway:[3.2,5.4],roll:[5.2,7.8],mouseShiftX:8,mouseShiftY:6,scrollFactor:.03,minWidthHideXL:640};let sky=null,emos=[],mx=.5,my=.5,rafId=null,scrollY=0,paused=false;const ensure=()=>{sky=document.querySelector(".emoji-sky");if(!sky){sky=document.createElement("div");sky.className="emoji-sky";sky.setAttribute("aria-hidden","true");document.body.prepend(sky)}return sky};const spawn=()=>{if(!sky)ensure();sky.innerHTML="";const pack=[];const add=(n,cls)=>{for(let i=0;i<n;i++){const em=document.createElement("span");em.className=`emo ${cls}`;em.textContent=CFG.emojis[(i+pack.length)%CFG.emojis.length];pack.push(em)}};add(CFG.density.xl,"xl");add(CFG.density.lg,"lg");add(CFG.density.md,"md");add(CFG.density.sm,"small");pack.sort(()=>Math.random()-.5).forEach(el=>sky.appendChild(el));emos=[...sky.querySelectorAll(".emo")];seedAll();responsiveCull()};const rand=(a,b)=>a+Math.random()*(b-a);const seedOne=(el)=>{el.style.left=`${rand(2,98)}%`;el.style.setProperty("--dur",`${rand(CFG.speed[0],CFG.speed[1])}s`);el.style.setProperty("--delay",`${rand(CFG.delay[0],CFG.delay[1])}s`);el.style.setProperty("--sway",`${rand(CFG.sway[0],CFG.sway[1])}s`);el.style.setProperty("--roll",`${rand(CFG.roll[0],CFG.roll[1])}s`);el.style.animationPlayState="paused";el.getBoundingClientRect();el.style.animationPlayState="running"};const seedAll=()=>emos.forEach(seedOne);const play=()=>{if(isReduced)return;emos.forEach(el=>el.style.animationPlayState="running");paused=false};const pause=()=>{emos.forEach(el=>el.style.animationPlayState="paused");paused=true};const parallax=()=>{const tx=(mx-.5)*CFG.mouseShiftX,ty=(my-.5)*CFG.mouseShiftY+(scrollY*CFG.scrollFactor);sky.style.transform=`translate3d(${tx}px,${ty}px,0)`;rafId=requestAnimationFrame(parallax)};const onMove=e=>{const x=(e.clientX??e.touches?.[0]?.clientX??innerWidth/2)/innerWidth;const y=(e.clientY??e.touches?.[0]?.clientY??innerHeight/2)/innerHeight;mx=x;my=y};const onScroll=throttle(()=>{scrollY=window.scrollY||0},80);const onVis=()=>{document.hidden?pause():play()};const responsiveCull=()=>{if(innerWidth<CFG.minWidthHideXL){emos.forEach((el,i)=>{if(el.classList.contains("xl")&&i%2===0)el.style.display="none";else el.style.display=""})}else{emos.forEach(el=>el.style.display="")}};const init=()=>{ensure();spawn();if(isReduced){pause()}else{play();cancelAnimationFrame(rafId);rafId=requestAnimationFrame(parallax)};on(window,"mousemove",onMove,{passive:true});on(window,"touchmove",onMove,{passive:true});on(window,"scroll",onScroll,{passive:true});on(document,"visibilitychange",onVis);on(window,"resize",throttle(responsiveCull,160))};init();return{config:(next={})=>Object.assign(CFG,next),refresh:()=>spawn(),pause,play}})(); /* 使用：EmojiSky.config({...}); EmojiSky.refresh(); */
/* ====== 對外 API（可選） ====== */
window.FatismApp=Object.freeze({setTheme:(t)=>{if(!["light","dark"].includes(t))return;document.documentElement.setAttribute("data-theme",t);localStorage.setItem("theme",t);if(themeIcon)themeIcon.textContent=t==="dark"?"🌙":"🌞"},emoji:EmojiSky});
/* ====== 初始化完成 ====== */
document.documentElement.classList.remove("no-js");
})();
/* REPLACE END: app.js（FATISM 多頁共用） */
